SET client_encoding = 'UTF8';


CREATE TABLE city (
    id bigserial constraint pk_city PRIMARY KEY,
    code_insee text UNIQUE,
    nom_standard text,
    nom_sans_pronom text,
    nom_a text,
    nom_de text,
    nom_sans_accent text,
    nom_standard_majuscule text,
    typecom text,
    typecom_texte text,
    reg_code text,
    reg_nom text,
    dep_code text,
    dep_nom text,
    canton_code text,
    canton_nom text,
    epci_code text,
    epci_nom text,
    academie_code text,
    academie_nom text,
    code_postal text,
    codes_postaux text,
    zone_emploi text,
    code_insee_centre_zone_emploi text,
    code_unite_urbaine text,
    nom_unite_urbaine text,
    taille_unite_urbaine double precision,
    type_commune_unite_urbaine text,
    statut_commune_unite_urbaine text,
    population bigint,
    superficie_hectare double precision,
    superficie_km2 double precision,
    densite double precision,
    altitude_moyenne double precision,
    altitude_minimale double precision,
    altitude_maximale double precision,
    latitude_mairie double precision,
    longitude_mairie double precision,
    latitude_centre double precision,
    longitude_centre double precision,
    grille_densite text,
    grille_densite_texte text,
    niveau_equipements_services double precision,
    niveau_equipements_services_texte text,
    gentile text,
    url_wikipedia text,
    url_villedereve text
);