package city.data;

import java.util.Objects;

/**
 * The class City represents a city with its name, ...
 */
public class CityFr { // NB: extends java.lang.Object

    public final static String NO_ZIPCODE = "pas de code postal";

    private String name;
    private String inseeCode;
    private String zipcode;
    private String departmentNumber;
    private int population;

    public CityFr() {
    }

    public CityFr(String name, String zipcode) {
        this.name = name;
        this.zipcode = zipcode;
    }

    public CityFr(String name, String inseeCode, String zipcode, String departmentNumber, int population) {
        this.name = name;
        this.inseeCode = inseeCode;
        this.zipcode = zipcode;
        this.departmentNumber = departmentNumber;
        this.population = population;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getInseeCode() {
        return inseeCode;
    }

    public void setInseeCode(String inseeCode) {
        this.inseeCode = inseeCode;
    }

    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getDepartmentNumber() {
        return departmentNumber;
    }

    public void setDepartmentNumber(String departmentNumber) {
        this.departmentNumber = departmentNumber;
    }

    public int getPopulation() {
        return population;
    }

    public void setPopulation(int population) {
        this.population = population;
    }

    // auto generated by intelliJ (method concat)
//    @Override
//    public String toString() {
//        return "CityFr{" +
//                "name='" + name + '\'' +
//                ", zipcode='" + zipcode + '\'' +
//                '}';
//    }

    @Override
    public String toString() {
        return  name
                + " ("
                // + ((zipcode == null) ? NO_ZIPCODE : zipcode)
                + Objects.toString(zipcode, NO_ZIPCODE) // Java 7
                + ')';
    }
}
